import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Mail, Newspaper, BriefcaseBusiness, FileText, ShieldCheck, Accessibility, MapPin, Phone, Clock, ArrowUpRight } from 'lucide-react';
import { Button, Band, Wordmark } from '@/components/ds/primitives';
import { Breadcrumbs, Container } from '@/components/ds/shell/layout-parts';
import { EnquiryForm } from '@/components/contact/EnquiryForm';
import { useContactContent } from '@/lib/contact-data';
import { CONTACT_COPY } from '@/lib/contact-copy';
import { useI18n } from '@/lib/i18n';
import type { ContactContent } from '@/lib/contact-schema';
function ContactDetails({details,lang}:{details:NonNullable<ContactContent['general']>;lang:'en'|'fr'|'pt'}){
 const c=CONTACT_COPY[lang];return <dl className="mt-6 grid gap-5 sm:grid-cols-2">{details.address&&<div><dt className="flex gap-2 text-small text-muted-foreground"><MapPin className="size-4" aria-hidden/>{c.address}</dt><dd className="mt-1 whitespace-pre-line">{[details.address,details.city,details.country].filter(Boolean).join('\n')}</dd></div>}{details.email&&<div><dt className="flex gap-2 text-small text-muted-foreground"><Mail className="size-4" aria-hidden/>{c.email}</dt><dd className="mt-1 break-all"><a href={`mailto:${details.email}`}>{details.email}</a></dd></div>}{details.phone&&<div><dt className="flex gap-2 text-small text-muted-foreground"><Phone className="size-4" aria-hidden/>{c.telephone}</dt><dd className="mt-1"><a href={`tel:${details.phone.replace(/[^+\d]/g,'')}`}>{details.phone}</a></dd></div>}{details.hours&&<div><dt className="flex gap-2 text-small text-muted-foreground"><Clock className="size-4" aria-hidden/>{c.hours}</dt><dd className="mt-1">{details.hours}</dd></div>}</dl>;
}
export default function ContactPage(){
 const {lang}=useI18n();const c=CONTACT_COPY[lang];const {content}=useContactContent(lang);const [type,setType]=useState('general');
 useEffect(()=>{const title='Contact OAG | Office of the Auditor General of ECOWAS Institutions';const description=CONTACT_COPY.en.lead;const previous=document.title;document.title=title;const restore:(()=>void)[]=[];for(const [selector,value] of [['meta[name="description"]',description],['meta[property="og:title"]',title],['meta[property="og:description"]',description]]){const node=document.querySelector(selector);if(node){const old=node.getAttribute('content')??'';node.setAttribute('content',value);restore.push(()=>node.setAttribute('content',old));}}return()=>{document.title=previous;restore.forEach(fn=>fn());};},[]);
 const choose=(value:string)=>{setType(value);document.getElementById('general-enquiry')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});requestAnimationFrame(()=>document.getElementById('contact-enquiry_type')?.focus({preventScroll:true}));};
 const icons=[Mail,Newspaper,BriefcaseBusiness,FileText,ShieldCheck,Accessibility];const destinations=['#general-enquiry','#media','/opportunities/careers','/opportunities/procurement','/integrityline','#accessibility-assistance'];
 return <div className="contact-hub">
 <header className="border-b border-border bg-card"><Container className="pb-12 pt-6 md:pb-14"><Breadcrumbs items={[{label:c.home,to:'/'},{label:c.contact}]}/><p className="mt-10 text-xs font-semibold text-primary">{c.eyebrow}</p><h1 className="mt-3 text-4xl font-bold leading-tight tracking-normal md:text-6xl">{c.title}</h1><p className="mt-6 max-w-3xl text-lg text-ink-soft">{c.lead}</p><p className="mt-3 max-w-3xl text-muted-foreground">{c.choose}</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3"><Button variant="primary" onClick={()=>choose('general')}>{c.channels[0][2]}<ArrowRight aria-hidden/></Button><Button asChild variant="tertiary"><a href="#help">{c.help}<ArrowRight aria-hidden/></a></Button></div></Container><Band/></header>
 <Container as="section" className="grid gap-8 py-10 md:grid-cols-[1fr_1.6fr] md:py-12"><div><p className="text-xs font-semibold text-primary">OAG · ECOWAS</p><h2 className="mt-3 text-xl font-bold">{c.office}</h2></div><div>{content?.general&&Object.values(content.general).some(Boolean)?<ContactDetails details={content.general} lang={lang}/>:<p className="border-l-2 border-border pl-5 text-muted-foreground">{c.officeNote}</p>}</div></Container>
 <section id="help" className="scroll-mt-28 border-y border-border bg-surface-sunken"><Container className="py-12"><h2 className="text-2xl font-bold">{c.help}</h2><div className="mt-8 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">{c.channels.map(([title,body,cta],i)=>{const Icon=icons[i];return <article key={title} className="flex min-w-0 flex-col border-t border-border py-7"><div className="flex items-center gap-3"><Icon className={`size-5 shrink-0 ${i===4?'text-ecowas-red':i===2||i===3?'text-ecowas-ocean':'text-primary'}`} aria-hidden/><h3 className="text-lg font-semibold">{title}</h3></div><p className="mt-3 flex-1 text-ink-soft">{body}</p><div className="mt-5">{i===0||i===5?<Button variant="tertiary" className="min-h-11 whitespace-normal text-left" onClick={()=>choose(i===5?'accessibility':'general')}>{cta}<ArrowRight aria-hidden/></Button>:<Button asChild variant="tertiary" className="min-h-11 whitespace-normal text-left">{destinations[i].startsWith('/')?<Link to={destinations[i]}>{cta}<ArrowRight aria-hidden/></Link>:<a href={destinations[i]}>{cta}<ArrowRight aria-hidden/></a>}</Button>}</div></article>;})}</div></Container></section>
 <Container as="section" className="grid gap-10 py-12 lg:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)] lg:gap-20"><div id="general-enquiry" className="scroll-mt-28"><h2 className="mb-7 text-2xl font-bold">{c.form}</h2><EnquiryForm lang={lang} type={type} onType={setType} content={content}/></div><aside className="min-w-0 border-t border-border pt-7 lg:border-t-0 lg:pt-0"><Wordmark compact/><h3 className="mt-6 text-lg font-semibold">{c.privacy}</h3><p className="mt-3 whitespace-pre-line text-small text-muted-foreground">{content?.privacy_notice??c.privacyPending}</p><div className="mt-9 border-t border-border pt-7"><ShieldCheck className="size-6 text-ecowas-red" aria-hidden/><h3 className="mt-3 text-lg font-semibold">{c.integrity}</h3><p className="mt-3 text-small text-ink-soft">{c.integrityBody}</p><Button asChild variant="tertiary" className="mt-4 min-h-11"><Link to="/integrityline">{c.integrityCta}<ArrowRight aria-hidden/></Link></Button></div></aside></Container>
 <section className="border-y border-border bg-card"><Container className="grid gap-10 py-12 md:grid-cols-2"><div id="location" className="scroll-mt-28"><MapPin className="size-7 text-primary" aria-hidden/><h2 className="mt-4 text-2xl font-bold">{c.location}</h2>{content?.general?.address?<><ContactDetails details={content.general} lang={lang}/><p className="mt-4 text-ink-soft">{content.general.visitor_information}</p>{content.general.map_url&&<Button asChild variant="tertiary" className="mt-4 min-h-11"><a href={content.general.map_url} target="_blank" rel="noreferrer">{c.map}<ArrowUpRight aria-hidden/></a></Button>}</>:<p className="mt-4 max-w-lg text-muted-foreground">{c.locationPending}</p>}</div><div id="media" className="scroll-mt-28 border-t border-border pt-8 md:border-l md:border-t-0 md:pl-10 md:pt-0"><Newspaper className="size-7 text-ecowas-ocean" aria-hidden/><h2 className="mt-4 text-2xl font-bold">{c.media}</h2><p className="mt-4 text-ink-soft">{c.mediaBody}</p>{content?.media&&<ContactDetails details={content.media} lang={lang}/>}<div className="mt-5 flex flex-wrap gap-4"><Button asChild variant="tertiary" className="min-h-11"><Link to="/news/media">{c.mediaCta}<ArrowRight aria-hidden/></Link></Button><Button variant="tertiary" className="min-h-11" onClick={()=>choose('media')}>{c.types[5]}<ArrowRight aria-hidden/></Button></div></div></Container></section>
 <section className="border-b border-border bg-ecowas-ocean text-primary-foreground"><Container className="grid items-start gap-8 py-10 md:grid-cols-[1fr_auto]"><div><ShieldCheck className="size-7 text-ecowas-yellow" aria-hidden/><h2 className="mt-4 text-2xl font-bold text-primary-foreground">{c.integrity}</h2><p className="mt-4 max-w-3xl text-primary-foreground/85">{c.integrityBody}</p></div><Button asChild variant="inverse" className="self-center whitespace-normal"><Link to="/integrityline">{c.integrityCta}<ArrowRight aria-hidden/></Link></Button></Container></section>
 <Container as="section" className="grid gap-12 py-12 md:grid-cols-2"><div id="accessibility-assistance" className="scroll-mt-28"><Accessibility className="size-7 text-primary" aria-hidden/><h2 className="mt-4 text-2xl font-bold">{c.access}</h2><p className="mt-4 text-ink-soft">{c.accessBody}</p>{content?.accessibility&&<ContactDetails details={content.accessibility} lang={lang}/>}<Button variant="tertiary" className="mt-5 min-h-11 whitespace-normal text-left" onClick={()=>choose('accessibility')}>{c.accessCta}<ArrowRight aria-hidden/></Button></div><div><h2 className="text-2xl font-bold">{c.faq}</h2>{content?.faqs?.length?<div className="mt-6">{content.faqs.map(faq=><details key={faq.question} className="border-t border-border py-4"><summary className="min-h-11 cursor-pointer py-2 font-semibold">{faq.question}</summary><p className="mt-3 whitespace-pre-line text-ink-soft">{faq.answer}</p></details>)}</div>:<p className="mt-4 text-muted-foreground">{c.faqPending}</p>}</div></Container>
 <section className="border-t border-border bg-primary-soft"><Container className="flex flex-wrap items-center justify-between gap-6 py-10"><div><h2 className="text-xl font-bold">{c.final}</h2><p className="mt-2 text-ink-soft">{c.finalBody}</p></div><Button asChild variant="secondary"><Link to="/about">{c.finalCta}<ArrowRight aria-hidden/></Link></Button></Container></section>
 </div>;
}
