import { Link } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, ScrollText, ShieldAlert, ChevronDown } from "lucide-react";
import { Button, Band, Wordmark } from "@/components/ds/primitives";
import { CAREER_AREAS, PROCESS_STEPS, FAQS } from "@/lib/careers-data";
import { NOTICE_TYPES, PARTICIPATION_STEPS, PROCUREMENT_FAQS } from "@/lib/procurement-data";
import { useI18n } from "@/lib/i18n";
import { NAV } from "@/lib/site";
import meetingImg from "@/assets/editorial-meeting.jpg";

function Questions({ items }: { items: { q: string; a: string }[] }) {
  return <div className="divide-y divide-border border-y border-border">{items.map((item) => <details key={item.q} className="group"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 py-4 font-semibold text-ink [&::-webkit-details-marker]:hidden">{item.q}<ChevronDown className="size-4 shrink-0 transition-transform group-open:rotate-180 motion-reduce:transition-none" aria-hidden /></summary><p className="pb-5 text-small text-ink-soft">{item.a}</p></details>)}</div>;
}

function Steps({ items }: { items: { title: string; body: string }[] }) {
  return <ol className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{items.map((item, i) => <li key={item.title} className="border-t-2 border-primary pt-4"><span className="font-mono text-small text-primary">0{i + 1}</span><h3 className="mt-2 font-display text-h4">{item.title}</h3><p className="mt-2 text-small text-ink-soft">{item.body}</p></li>)}</ol>;
}

export default function Opportunities() {
  const { lang } = useI18n();
  const section = NAV.find((item) => item.slug === "opportunities");
  const careersLabel = section?.children[0]?.label[lang] ?? "Careers";
  const procurementLabel = section?.children[1]?.label[lang] ?? "Procurement";
  return <div lang="en">
    <section className="container py-section-sm">
      
      <div className="flex flex-wrap items-end justify-between gap-6"><div><p className="overline text-primary">Work with the Office</p><h1 className="mt-3 font-display text-h1">{section?.label[lang] ?? "Opportunities"}</h1><p className="mt-4 max-w-2xl text-lead text-ink-soft">Careers and procurement at the Office of the Auditor General of ECOWAS Institutions.</p></div><Wordmark compact /></div>
      <div className="mt-8 grid gap-5 md:grid-cols-2">
        {[{ title: careersLabel, icon: BriefcaseBusiness, body: "Professional roles, internships and consultancy opportunities. Find approved vacancy notices and their application requirements.", action: "View current vacancies", to: "/opportunities/careers" }, { title: procurementLabel, icon: ScrollText, body: "Calls for tenders, expressions of interest and requests for quotation. Find published notices and their submission requirements.", action: "View procurement notices", to: "/opportunities/procurement" }].map(({ title, icon: Icon, body, action, to }) => <article key={to} className="flex flex-col border border-border border-t-4 border-t-primary bg-card p-6"><div className="flex items-center gap-3"><Icon className="size-6 text-primary" aria-hidden /><h2 className="font-display text-h3">{title}</h2></div><p className="mt-3 max-w-xl flex-1 text-body text-ink-soft">{body}</p><Button asChild className="mt-6 self-start max-w-full whitespace-normal text-left"><Link to={to}>{action}<ArrowRight /></Link></Button></article>)}
      </div>
      <nav aria-label="Opportunity guidance" className="mt-7 flex flex-wrap gap-x-6 gap-y-2 border-b border-border pb-4 text-small font-semibold text-primary"><a href="#careers-guidance" className="py-2 hover:underline">Careers guidance</a><a href="#procurement-guidance" className="py-2 hover:underline">Procurement guidance</a><a href="#faqs" className="py-2 hover:underline">Frequently asked questions</a></nav>
    </section>
    <section className="bg-ecowas-yellow-12"><div className="container flex flex-col gap-5 py-7 md:flex-row md:items-center"><ShieldAlert className="size-7 shrink-0 text-accent" aria-hidden /><div className="flex-1"><h2 className="font-display text-h4">Do not pay to apply or participate</h2><p className="mt-2 text-small text-ink-soft">The OAG never asks for payment at any stage of recruitment or to participate in procurement. Check the official notice and use only the application or submission channel it names. Report suspicious requests through IntegrityLine.</p></div><Button asChild variant="secondary" className="self-start md:self-center"><Link to="/integrityline">Report a concern <ArrowRight /></Link></Button></div></section>
    <section id="careers-guidance" className="container scroll-mt-28 py-section">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><p className="overline text-primary">For applicants</p><h2 className="mt-3 font-display text-h2">Careers guidance</h2></div><Button asChild variant="tertiary"><Link to="/opportunities/careers">Current vacancies <ArrowRight /></Link></Button></div>
      <div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><img src={meetingImg} alt="Colleagues working together in a meeting" loading="lazy" className="aspect-[4/3] w-full object-cover" /><p className="mt-4 text-small text-muted-foreground">Eligibility, qualifications and application requirements are set out in each published vacancy notice.</p></div><div><h3 className="font-display text-h3">Career areas</h3><ul className="mt-5 grid gap-x-6 sm:grid-cols-2">{CAREER_AREAS.map((area) => <li key={area.id} className="border-t border-border py-4"><h4 className="font-semibold">{area.title}</h4><p className="mt-2 text-small text-ink-soft">{area.summary}</p></li>)}</ul></div></div>
      <h3 className="mb-6 mt-10 font-display text-h3">How recruitment works</h3><Steps items={PROCESS_STEPS} />
    </section>
    <section id="procurement-guidance" className="scroll-mt-28 bg-surface-sunken"><div className="container py-section"><div className="mb-8 flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><p className="overline text-primary">For suppliers and partners</p><h2 className="mt-3 font-display text-h2">Procurement guidance</h2></div><Button asChild variant="tertiary"><Link to="/opportunities/procurement">Current notices <ArrowRight /></Link></Button></div><div className="grid gap-8 md:grid-cols-2"><div><h3 className="font-display text-h3">Published notice types</h3><ul className="mt-4 divide-y divide-border">{NOTICE_TYPES.map((type) => <li key={type.id} className="flex items-center gap-3 py-3 text-body"><ScrollText className="size-4 text-primary" aria-hidden />{type.title}</li>)}</ul></div><div><h3 className="font-display text-h3">Donor-funded procurement</h3><p className="mt-4 text-body text-ink-soft">Some procurement is financed under agreements with development partners and follows the procedures required by those agreements. Eligibility rules may differ from those financed directly by ECOWAS. Follow the requirements in the published notice.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3">{["Plans", "Awards", "Projects", "Resources"].map((label) => <Button key={label} asChild variant="tertiary" size="sm"><Link to={`/opportunities/procurement/${label.toLowerCase()}`}>{label}<ArrowRight /></Link></Button>)}</div></div></div><h3 className="mb-6 mt-10 font-display text-h3">How to participate</h3><Steps items={PARTICIPATION_STEPS} /></div></section>
    <section id="faqs" className="container scroll-mt-28 py-section"><h2 className="font-display text-h2">Frequently asked questions</h2><div className="mt-8 grid gap-10 lg:grid-cols-2"><div id="careers-faqs" className="scroll-mt-28"><h3 className="mb-5 font-display text-h3">Careers</h3><Questions items={FAQS} /></div><div id="procurement-faqs" className="scroll-mt-28"><h3 className="mb-5 font-display text-h3">Procurement</h3><Questions items={PROCUREMENT_FAQS} /></div></div></section>
    <section className="bg-primary text-primary-foreground"><div className="container flex flex-wrap items-center justify-between gap-6 py-8"><h2 className="font-display text-h3 text-primary-foreground">Explore published opportunities</h2><div className="flex flex-wrap gap-3"><Button asChild variant="inverse"><Link to="/opportunities/careers">Current vacancies <ArrowRight /></Link></Button><Button asChild variant="inverse"><Link to="/opportunities/procurement">Procurement notices <ArrowRight /></Link></Button></div></div><Band /></section>
  </div>;
}