import { useRef, useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ds/primitives';
import { enquirySchema, ENQUIRY_TYPES, SUBMISSIONS_OPEN, type ContactContent } from '@/lib/contact-schema';
import { CONTACT_COPY } from '@/lib/contact-copy';
import type { Lang } from '@/lib/i18n';
export function EnquiryForm({lang,type,onType,content}:{lang:Lang;type:string;onType:(v:string)=>void;content?:ContactContent}){
 const c=CONTACT_COPY[lang];const [message,setMessage]=useState('');const [errors,setErrors]=useState<Record<string,string>>({});const summary=useRef<HTMLDivElement>(null);
 const countries=new Intl.DisplayNames([lang],{type:'region'});const codes='DZ AO BJ BW BF BI CV CM CF TD KM CG CD CI DJ EG GQ ER SZ ET GA GM GH GN GW KE LS LR LY MG MW ML MR MU MA MZ NA NE NG RW ST SN SC SL SO ZA SS SD TZ TG TN UG ZM ZW US GB FR PT DE BE NL ES IT CA BR IN CN JP'.split(' ').map(code=>({code,name:countries.of(code)??code})).sort((a,b)=>a.name.localeCompare(b.name,lang));
 const control='mt-2 min-h-11 w-full rounded-md border border-input bg-card px-3 py-2 text-body';
 function validate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const result=enquirySchema.safeParse({...data,preferred_language:lang,consent_recorded:data.consent_recorded==='on'});if(!result.success){const e:Record<string,string>={};for(const issue of result.error.issues){const field=String(issue.path[0]);e[field]=field==='email'?c.invalidEmail:field==='consent_recorded'?c.consentError:c.invalid;}setErrors(e);requestAnimationFrame(()=>summary.current?.focus());}else setErrors({});}
 const labels:Record<string,string>={first_name:c.first,last_name:c.last,email:c.email,organization:c.organization,subject:c.subject};
 return <form noValidate onSubmit={validate} className="min-w-0" aria-describedby="submission-notice">
 <div id="submission-notice" role="status" className="mb-8 flex gap-3 border-l-4 border-ecowas-yellow bg-ecowas-yellow-12 p-5"><LockKeyhole className="mt-1 size-5 shrink-0 text-ecowas-ocean" aria-hidden/><div><p className="font-semibold">{c.closed}</p><p className="mt-1 text-small text-ink-soft">{c.closedBody}</p></div></div>
 {Object.keys(errors).length>0&&<div ref={summary} tabIndex={-1} role="alert" className="mb-6 border border-destructive p-4"><h3>{c.error}</h3><ul>{Object.entries(errors).map(([field,error])=><li key={field}><a href={`#contact-${field}`}>{labels[field]??(field==='message'?c.message:field==='enquiry_type'?c.type:c.consent)}: {error}</a></li>)}</ul></div>}
 <div className="grid gap-x-6 gap-y-5 sm:grid-cols-2">{Object.entries(labels).map(([field,label])=><div key={field} className={field==='subject'?'sm:col-span-2':''}><label htmlFor={`contact-${field}`} className="font-semibold">{label} <span className="ml-1 text-small font-normal text-muted-foreground">({field==='organization'?c.optional:c.required})</span></label><input id={`contact-${field}`} name={field} type={field==='email'?'email':'text'} required={field!=='organization'} autoComplete={field==='first_name'?'given-name':field==='last_name'?'family-name':field==='email'?'email':field==='organization'?'organization':'off'} maxLength={field==='email'?255:field==='subject'||field==='organization'?200:100} className={control} aria-invalid={!!errors[field]} aria-describedby={errors[field]?`${field}-error`:undefined}/>{errors[field]&&<p id={`${field}-error`} className="mt-1 text-small text-destructive">{errors[field]}</p>}</div>)}
 <div><label htmlFor="contact-country" className="font-semibold">{c.country} <span className="text-small font-normal text-muted-foreground">({c.optional})</span></label><select id="contact-country" name="country" className={control}><option value="">{c.select}</option>{codes.map(country=><option key={country.code} value={country.code}>{country.name}</option>)}</select></div>
 <div><label htmlFor="contact-enquiry_type" className="font-semibold">{c.type} <span className="text-small font-normal text-muted-foreground">({c.required})</span></label><select id="contact-enquiry_type" name="enquiry_type" value={type} onChange={e=>onType(e.target.value)} className={control}>{ENQUIRY_TYPES.map((value,i)=><option key={value} value={value}>{content?.categories?.find(cat=>cat.value===value)?.label??c.types[i]}</option>)}</select></div>
 <div className="sm:col-span-2"><label htmlFor="contact-message" className="font-semibold">{c.message} <span className="text-small font-normal text-muted-foreground">({c.required})</span></label><textarea id="contact-message" name="message" required maxLength={5000} rows={7} value={message} onChange={e=>setMessage(e.target.value)} className={`${control} resize-y`} aria-invalid={!!errors.message} aria-describedby="message-count message-error"/><p id="message-count" className="mt-1 text-right text-small text-muted-foreground" aria-live="polite">{5000-message.length} {c.remaining}</p><p id="message-error" className="text-small text-destructive">{errors.message}</p></div>
 </div><label className="my-6 flex min-h-11 items-start gap-3 text-small text-ink-soft"><input id="contact-consent_recorded" type="checkbox" name="consent_recorded" className="mt-1 size-5 shrink-0 accent-primary" aria-invalid={!!errors.consent_recorded}/><span>{c.consent}</span></label>
 <Button type="submit" disabled={!SUBMISSIONS_OPEN} className="w-full sm:w-auto"><LockKeyhole aria-hidden/>{c.send}</Button>
 </form>;
}
